### ISSUE TITLE
GPG files are not supported?

### ISSUE THREAD

**Issue by AnubhavKafle** [blachlylab/pyega#3]
Hi

I was wondering if you could help me download .gpg files from EGA using pyega. Is there a suppot for these files or any other easy way of downloading them?

**Comment by jblachly** [comment]
@AnubhavKafle Thanks for opening an issue.

The EMBL/EBI actually liked _pyega_ so much that they have forked the codebase to build _pyega3_.  @AlexanderSenf is now in charge of this, and you can find the correct repository location here: https://github.com/EGA-archive/ega-download-client 

I will try to mark this repository as archived and redirect to the updated version @ EMBL's github account. Sorry for the confusion. 

Best wishes
