### ISSUE TITLE
throttling / reserved bandwidth

### ISSUE THREAD

**Issue by j4jes** [blachlylab/pyega#5]
Thanks for the recent updates to pyega. I've noticed that downloading with multiple channels / streams has been very good lately. I'm wondering if there is any way to throttle pyega, so if I am downloading with many streams I could reserve a set amount of the bandwidth for business critical apps (ex. apache httpd). Is this more of a general linux request ?

**Comment by jblachly** [comment]
EGA have taken over development; please re-open in the official EGA repo https://github.com/EGA-archive/ega-download-client
